// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7AIeVxKBCwPhSrUQgvUUwC77G_kb3hvk',
    appId: '1:843378697012:web:c16ac117656935e48e7b61',
    messagingSenderId: '843378697012',
    projectId: 'fire-some-c3c9f',
    authDomain: 'fire-some-c3c9f.firebaseapp.com',
    storageBucket: 'fire-some-c3c9f.appspot.com',
    measurementId: 'G-2W5V21JET3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB20o0sTDaWEzhPtt0LM5QY6Mwrwf_x9j8',
    appId: '1:843378697012:android:d10044bd194f26348e7b61',
    messagingSenderId: '843378697012',
    projectId: 'fire-some-c3c9f',
    storageBucket: 'fire-some-c3c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0BVz3mIqzZQ1YvEWuwUrxcjmFUhTIEho',
    appId: '1:843378697012:ios:b4900a7854cccbbb8e7b61',
    messagingSenderId: '843378697012',
    projectId: 'fire-some-c3c9f',
    storageBucket: 'fire-some-c3c9f.appspot.com',
    iosClientId: '843378697012-vbsbred8d45vl4msn37dcdlsdgn32qae.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
